### ISSUE TITLE
Unable to Sync

### ISSUE THREAD

**Issue by bajmhunter** [CyferShepard/Jellystat#163]
JellyStat will not sync any details from Jellyfin.  It claims it can connect to my server using its IP/Port but every command run comes back with "No Libraries Found to Sync"  

Its running in the official Docker container and the only logs coming out of it is this over and over again.

Error {
  ErrorAt: 'at AxiosError.from (/app/node_modules/axios/dist/node/axios.cjs:837:14',
  Message: 'connect ECONNREFUSED 127.0.0.1:80'
}

Any help is much appriciated

**Environment Details (please complete the following information):**
 - OS: Docker container running on Debian
 - Browser: Edge
 - Jellystat Version 1.0.9
 - Jellyfin Version 10.8.13

**Comment by CyferShepard** [comment]
hi, can you try changing the url to the UP of the container and not 127.0.0.1, using 127.0.0.1 will resolve internally inside the docker container hosting jellystat. also i see your using port 80, unless you have port 8096 which is jellyfins default remapped to port 80, this would not work when poling data

**Comment by bajmhunter** [comment]
Hey, thanks for getting back so quickly.

I'm not using 127.0.0.1:80 for any of the images.  The IP address supplied to JellyStat when setting it up was a 172.16 range, with the port number (8096) appended to the end of it.  I'm not sure where the 127.0.0.1 in the logs is coming from.

I've tried using the IP address of the JF server, the host name, and various combinations with and without http:// or port numbers. but the error message remains the same.

**Comment by CyferShepard** [comment]
Sorry i took so long to get back. I did some digging and honestly this bug makes no sense, its possibly a network issue in docker because i managed to create an environment to replicate this use case and my message contained the ip address i specified. Can you try the following: Check in docker if the network mode is set to bridge and not host. Try and set the ip again, and if all else fails, recreate the postgres container, ensuring that you delete the files for postgres as itl just restore from the files your old install

**Comment by CyferShepard** [comment]
hey @bajmhunter , by any chance are you running on an arm platform?

**Comment by bajmhunter** [comment]
Hey, It was actually an arm64 platform that's been giving me issues.  

I've moved it onto an amd64 host now and everything seems to be behaving itself.  I think it might have been a networking issue as you mentioned in your last post host vs bridged.  It runs fine as bridged, but using host or a custom network interface with a static IP seems to return the same error.

**Comment by jaxgun** [comment]
I just want to throw a bit into this one. I setup jellystat today which threw the same error showing the 127.0.0.1 IP. I am using custom networks with a static IP. All I had to do was add the bridge as an option in the compose config, now it is working fine strangely enough. I still need to wait for the sync to finish though. My reverse proxy is using the static IP and so is jellystat. Postgres is using a custom internal network with a static IP as well with no issues.

**Comment by CyferShepard** [comment]
hey @jaxgun , so far we believe its an issue specific to the arm platform. Can you tell me what device your running on?

**Comment by jaxgun** [comment]
Running docker on NixOS VM under proxmox host. Nothing arm here. I should have mentioned that, apologies.

**Comment by Pesoen** [comment]
had same problem, running on a raspberry pi 4, changing docker image used from "latest" to "unstable" solves the issue, but with "latest" no ip and port config works.

i too believe the issue is ARM specific, but no clue where or why, but the "unstable" docker image works, so something must be changed between "latest" and "unstable" that fixes it.

**Comment by CyferShepard** [comment]
Hey @Pesoen , I just pushed a fix to `unstable` for arm not too long ago, this should be why its working, I'm still testing at the moment incase any other unexpected issues arise. 

To be honest I'm also not sure what the specific issue was, all I did was fix some inconsistent variable names, I guess arm compilers are less forgiving that x86 ones in that regard. But hopefully this is the actual fix and everything is stable.

**Comment by Pesoen** [comment]
@CyferShepard that is possible, but it also worked a week or so ago on unstable. but due to low system resources, i took jellystat down, but now that i have a few more raspberry pi's in my house, i am starting to setup stuff i removed again.

on another note, i wanted to move jellystat, as i put it on the wrong pi, now i cannot get it working again. so something odd is going on. on the wrong pi, i started with latest, which failed, then switched to unstable, and it worked, then i realized it was on the wrong pi, so i moved it to the one i wanted to use(different ram amount) and now it fails no matter what.

internal ip with port gets a "successfully updated" box, but will not sync. same with external(jellyfin.DOMAIN.EXTENSION)

very interesting behaviour, since both pi's are running the same dietpi image, with the same updates.

i am getting spammed in the log for jellystat though.
`Error {
  ErrorAt: 'at AxiosError.from (/app/node_modules/axios/dist/node/axios.cjs:837:14',
  Message: 'connect ECONNREFUSED 127.0.0.1:80'
}`
not sure what that means or why it gives an error, but maybe you know.

**Comment by CyferShepard** [comment]
So im testing on a Pi5 but running ubuntu, il need to retest this on DietPi, sadly i dont have a Pi4 so hopefully its not an issue specific to the Pi4

**Comment by JackTorrance1** [comment]
Hi, I am having the same error:
Error { ErrorAt: 'at AxiosError.from (/app/node_modules/axios/dist/node/axios.cjs:837:14', Message: 'connect ECONNREFUSED 127.0.0.1:80' }.
I tried latest and unstable. I am using Docker on Windows (not bridge mode). I had it working a few months ago, but I can't anymore.

**Comment by jjnj023** [comment]
I have the same issue here. Running in a proxmox container on debian. 
If i can support with any additional information or logs, please let me know.

`jellystat-jellystat-1     | Error {
jellystat-jellystat-1     |   ErrorAt: 'at AxiosError.from (/app/node_modules/axios/dist/node/axios.cjs:837:14',
jellystat-jellystat-1     |   Message: 'connect ECONNREFUSED 127.0.0.1:80'
jellystat-jellystat-1     | }
jellystat-jellystat-1 exited with code 0
jellystat-jellystat-1 exited with code 137`

**Comment by CatoTheDuck** [comment]
Had the same problem.
While setting Jellystat up, the format "https://jellystat.domain.tld/" didn't work. So I used "jellystat.domain.tld", which was accepted.

After that, I ran into the same error.

Changed "jellystat.domain.tld" to "https://jellystat.domain.tld" (without the trailing /) in the settings, restarted the container and then it worked.

Maybe that'll work for you!

**Comment by Pesoen** [comment]
restart fixed mine, still not on the right pi(due to issues with the os i was testing on it) but it's progress.. added the jellyfin using just the ip, and it fails to fetch data, add http:// to the front, save and restart container, it is now synchronizing. so it seems it might be a few issues, one of which is that it does not seem to use the new settings until the container is restarted(or maybe just the underlying program, unsure on that one)

going to test on the "correct" pi when i get it more stable if this is the case on that one as well. but for now keeping it running on the "wrong" pi while its working and the "correct" one is not.

**Comment by Pesoen** [comment]
still working today, only minor issue i have with it for now is that i cannot set the interval for Recently Added Items less than 12 hours, or more than 1, would ideally like to have it set to 4, but that is a minor complaint. i will try to transfer the stack over during the day to the "correct" pi, and just stopping it on the "wrong" one until it is fully up and running.

but so far it seems i can add jellyfin with the ip and port, and it can see it, but i need to add http:// in front of the ip to get it fully working, and then restart the container for the change to take effect(hitting save seems to save the setting, but not change it anywhere)

on my "correct" pi, i will try adding jellyfin with http://ip:port as the first thing, and if that fails, i am unsure what is causing the issues, other than oddities in the code somewhere.

**Comment by Codex966** [comment]
> but so far it seems i can add jellyfin with the ip and port, and it can see it, but i need to add http:// in front of the ip to get it fully working, and then restart the container for the change to take effect(hitting save seems to save the setting, but not change it anywhere)

Was having the same issue, just set everything up on unraid and could not get it to sync, was having the 127.0.0.1:80 error... 
tried postgres14 and 15, jellystat latest and unstable... Nothing.

Adding http:// to the jellyfin address inside jellystat and giving it a restart seemed to fix it.

**Comment by Pesoen** [comment]
so a possible fix for the issue, is to check if the address starts with http or https, and if it does not, add it before doing anything else, or require it before validating it. and maybe look into adding an automatic restart when changes to settings is made, so we don't have to restart it manually when changing certain settings.

@bajmhunter can you try this as well, setting the address to http://ip:port and restarting the container to see if that works?

**Comment by bajmhunter** [comment]
> so a possible fix for the issue, is to check if the address starts with http or https, and if it does not, add it before doing anything else, or require it before validating it. and maybe look into adding an automatic restart when changes to settings is made, so we don't have to restart it manually when changing certain settings.
> 
> @bajmhunter can you try this as well, setting the address to http://ip:port and restarting the container to see if that works?

I'll get that looked at tonight and let you know how it goes. Thanks

**Comment by Pesoen** [comment]
> > so a possible fix for the issue, is to check if the address starts with http or https, and if it does not, add it before doing anything else, or require it before validating it. and maybe look into adding an automatic restart when changes to settings is made, so we don't have to restart it manually when changing certain settings.
> > @bajmhunter can you try this as well, setting the address to http://ip:port and restarting the container to see if that works?
> 
> I'll get that looked at tonight and let you know how it goes. Thanks

soo, did it work? i am curious :)

**Comment by dandud100** [comment]
For me I got a "No Libraries Found to Sync" because I forgot to set a backup path while setting up my unraid docker container I think.

**Comment by coreytyhurst** [comment]
Confirming that the fix above, adding "http://" before the local ip, in my case "http://192.168.30.20:8096" and then restarting the container fixed the trick.
