### ISSUE TITLE
Full Jellyfin Sync failing on "large" Music library

### ISSUE THREAD

**Issue by kamilkosek** [CyferShepard/Jellystat#255]
On a "large" music library  (~40k Tracks) , the sync is failing with only the message: 
```
Syncing... 1/7
Beginning User Sync
16 Rows Inserted.
User Sync Complete
Syncing... 2/7
Beginning Library Sync
3 Rows Inserted.
Syncing... 3/7
Beginning Library Item Sync
Error performing bulk insert:Bulk insert error: error: invalid message format
at sync.insertData (/app/backend/routes/sync.js:56:13: Error: Error: Error performing bulk insert:Bulk insert error: error: invalid message format
```
I think it has something to do with the size of the library as the [insertBulk](https://github.com/CyferShepard/Jellystat/blob/e691980b6c6b2f339fae644abc549bce77d694c0/backend/db.js#L88) function tries to insert it all at once - maybe theres a limit, but dont know

**Comment by CyferShepard** [comment]
Hey @kamilkosek , can you provide me with the below information. 
**Environment Details:**
 - OS: [e.g. Ubuntu]
 - Browser [e.g. chrome, Mozilla]
 - Jellystat Version [e.g. 1.0.0]
 - Jellyfin Version [e.g. 10.0.5]

**Container Logs**
If applicable, add Container Logs for your problem.

**Comment by kamilkosek** [comment]
Sure :)
Jellystat 1.1.0 in Docker container
Chrome based most recent browser
Jellyfin 10.9.10

The container logs doesn´t say much:
```
[JELLYSTAT] Database exists. Skipping creation
FS-related option specified for migration configuration. This resets migrationSource to default FsMigrations
FS-related option specified for migration configuration. This resets migrationSource to default FsMigrations
[JELLYSTAT] Server listening on http://127.0.0.1:3000
```
The logs inside Jellystat: 

```
Syncing... 1/7
Beginning User Sync
16 Rows Inserted.
User Sync Complete
Syncing... 2/7
Beginning Library Sync
3 Rows Inserted.
Syncing... 3/7
Beginning Library Item Sync
Error performing bulk insert:Bulk insert error: error: invalid message format
at sync.insertData (/app/backend/routes/sync.js:56:13: Error: Error: Error performing bulk insert:Bulk insert error: error: invalid message format
```

**Comment by Nostradamus1973** [comment]
Has anyone found a fix for this?
I'm getting the same error in the logs:
```
Error performing bulk insert:Bulk insert error: error: invalid message format
at sync.insertData (/app/backend/routes/sync.js:55:13: Error: Error: Error performing bulk insert:Bulk insert error: error: invalid message format
```
OS: Ubuntu 24.04
Browser : Tried on  Chrome and Mozilla
Jellystat Version: 1.1.1
Jellyfin Version: 10.10.3

Thank you and have a nice day.

**Comment by sirelewop14** [comment]
I'm also seeing this happen on one of my libraries:


Log output from sync in web gui:

`Syncing... 1/4

Beginning User Sync

User Sync Complete

Syncing... 2/4

Beginning Library Sync

Library Sync Complete

Syncing... 3/4

Beginning Media Sync

Error performing bulk insert:Bulk insert error: error: invalid message format

at sync.insertData (/app/backend/routes/sync.js:55:13: Error: Error: Error performing bulk insert:Bulk insert error: error: invalid message format`


And log output from container:

`env.js file has been saved successfully.
[JELLYSTAT] Database exists. Skipping creation
FS-related option specified for migration configuration. This resets migrationSource to default FsMigrations
FS-related option specified for migration configuration. This resets migrationSource to default FsMigrations
[JELLYSTAT] Server listening on http://127.0.0.1:3000
Removed Data from WD Count:  1
Activity inserted/updated Count:  1
New Data Inserted:  1
Running Scheduled Sync
Running Scheduled Backup
Scheduled Backup Complete
Scheduled Sync Complete
Running Recently Added Scheduled Sync
Scheduled Recently Added Sync Complete
Removed Data from WD Count:  1
TypeError: Cannot read properties of undefined (reading 'length')
    at Timeout.intervalCallback (/app/backend/tasks/FullSyncTask.js:61:18)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
New Data Inserted:  1
Removed Data from WD Count:  1
Activity inserted/updated Count:  1
New Data Inserted:  1
New Data Inserted:  1
Removed Data from WD Count:  1
Activity inserted/updated Count:  1`


Jellystat version 1.1.3
Jellyfin version 10.10.6
Postgres DB: 17.4 

Both apps and the PG database are running in docker on the same physical host under unRAID 7.0.1
