### ISSUE TITLE
Emby: Active Sessions not displayed on Jellystat homepage

### ISSUE THREAD

**Issue by needo37** [CyferShepard/Jellystat#272]
**Describe the bug**
Active Sessions do not show up in Jellystat from Emby

**Environment Details (please complete the following information):**
 - OS: MacOS - Client. Ubuntu - Server
 - Browser: Mozilla/Safari
 - Jellystat Version 1.1.1 and unstable
 - Emby Version 4.8.10.0

**To Reproduce**
Open up your jellystat homepage after configuring Emby. Verify someone is watching something in Emby.

Hit refresh on Jellystat and nothing shows up under Active Sessions.

Look in embyserver.txt to see the errors.

**Expected behavior**
Active sessions show up in jellystat

**Task Logs**
N/A

**Container Logs**
`
2024-12-04 13:40:18.956 Error Server: Error processing request
	*** Error Report ***
	Version: 4.8.10.0
	Command line: /opt/emby-server/system/EmbyServer.dll -programdata /var/lib/emby -ffdetect /opt/emby-server/bin/ffdetect -ffmpeg /opt/emby-server/bin/ffmpeg -ffprobe /opt/emby-server/bin/ffprobe -restartexitcode 3 -updatepackage emby-server-deb_{version}_amd64.deb
	Operating system: Linux version 6.8.12-2-pve (build@proxmox) (gcc (Debian 12.2.0-14) 12.2.0, GNU ld (GNU Binutils for Debian) 2.40) #1 SMP PREEMPT_DYNAMIC PMX 6.8.12-2
	Framework: .NET 6.0.31
	OS/Process: x64/x64
	Runtime: opt/emby-server/system/System.Private.CoreLib.dll
	Processor count: 56
	Data path: /var/lib/emby
	Application path: /opt/emby-server/system
	System.FormatException: System.FormatException: Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).
	   at System.Guid.GuidResult.SetFailure(Boolean overflow, String failureMessageID)
	   at System.Guid.TryParseExactN(ReadOnlySpan`1 guidString, GuidResult& result)
	   at System.Guid.TryParseGuid(ReadOnlySpan`1 guidString, GuidResult& result)
	   at Emby.Server.Implementations.Library.LibraryManager.GetInternalId(ReadOnlySpan`1 id)
	   at Emby.Server.Implementations.Library.LibraryManager.GetInternalId(String id)
	   at Emby.Api.Images.ImageService.Get(GetItemImage request)
	   at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost appHost, Object requestDto, IRequest req, Type serviceType)
	   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IServerApplicationHost appHost, IRequest httpReq, IResponse httpRes, IStreamHelper streamHelper, RestPath restPath, String responseContentType, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IRequest httpReq, ReadOnlyMemory`1 urlString, ReadOnlyMemory`1 localPath, CancellationToken cancellationToken)
	Source: System.Private.CoreLib
	TargetSite: Void SetFailure(Boolean, System.String)

2024-12-04 13:40:18.956 Info Server: http/1.1 Response 500 to ‌‍‍10.0.1.9‌. Time: 1ms. GET http://‌‍‍emby‌:8096/Items/undefined/Images/Backdrop?fillWidth=300&quality=10&blur=0
2024-12-04 13:40:18.956 Error Server: Error processing request
	*** Error Report ***
	Version: 4.8.10.0
	Command line: /opt/emby-server/system/EmbyServer.dll -programdata /var/lib/emby -ffdetect /opt/emby-server/bin/ffdetect -ffmpeg /opt/emby-server/bin/ffmpeg -ffprobe /opt/emby-server/bin/ffprobe -restartexitcode 3 -updatepackage emby-server-deb_{version}_amd64.deb
	Operating system: Linux version 6.8.12-2-pve (build@proxmox) (gcc (Debian 12.2.0-14) 12.2.0, GNU ld (GNU Binutils for Debian) 2.40) #1 SMP PREEMPT_DYNAMIC PMX 6.8.12-2
	Framework: .NET 6.0.31
	OS/Process: x64/x64
	Runtime: opt/emby-server/system/System.Private.CoreLib.dll
	Processor count: 56
	Data path: /var/lib/emby
	Application path: /opt/emby-server/system
	MediaBrowser.Common.Extensions.ResourceNotFoundException: MediaBrowser.Common.Extensions.ResourceNotFoundException: 3 does not have an image of type Backdrop
	   at Emby.Api.Images.ImageService.GetImage(ImageRequest request, Int64 itemId, BaseItem item, Boolean isHeadRequest)
	   at Emby.Server.Implementations.Services.ServiceController.GetTaskResult(Task task)
	   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IServerApplicationHost appHost, IRequest httpReq, IResponse httpRes, IStreamHelper streamHelper, RestPath restPath, String responseContentType, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IRequest httpReq, ReadOnlyMemory`1 urlString, ReadOnlyMemory`1 localPath, CancellationToken cancellationToken)
	Source: Emby.Api
	TargetSite: Void MoveNext()

2024-12-04 13:40:18.956 Info Server: http/1.1 Response 404 to ‌‍‍10.0.1.9‌. Time: 1ms. GET http://‌‍‍emby‌:8096/Items/3/Images/Backdrop?fillWidth=300&quality=10&blur=0
2024-12-04 13:40:18.973 Error Server: Error processing request
	*** Error Report ***
	Version: 4.8.10.0
	Command line: /opt/emby-server/system/EmbyServer.dll -programdata /var/lib/emby -ffdetect /opt/emby-server/bin/ffdetect -ffmpeg /opt/emby-server/bin/ffmpeg -ffprobe /opt/emby-server/bin/ffprobe -restartexitcode 3 -updatepackage emby-server-deb_{version}_amd64.deb
	Operating system: Linux version 6.8.12-2-pve (build@proxmox) (gcc (Debian 12.2.0-14) 12.2.0, GNU ld (GNU Binutils for Debian) 2.40) #1 SMP PREEMPT_DYNAMIC PMX 6.8.12-2
	Framework: .NET 6.0.31
	OS/Process: x64/x64
	Runtime: opt/emby-server/system/System.Private.CoreLib.dll
	Processor count: 56
	Data path: /var/lib/emby
	Application path: /opt/emby-server/system
	MediaBrowser.Common.Extensions.ResourceNotFoundException: MediaBrowser.Common.Extensions.ResourceNotFoundException: kanethepuppy does not have an image of type Primary
	   at Emby.Api.Images.ImageService.GetImage(ImageRequest request, Int64 itemId, BaseItem item, Boolean isHeadRequest)
	   at Emby.Server.Implementations.Services.ServiceController.GetTaskResult(Task task)
	   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IServerApplicationHost appHost, IRequest httpReq, IResponse httpRes, IStreamHelper streamHelper, RestPath restPath, String responseContentType, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IRequest httpReq, ReadOnlyMemory`1 urlString, ReadOnlyMemory`1 localPath, CancellationToken cancellationToken)
	Source: Emby.Api
	TargetSite: Void MoveNext()

2024-12-04 13:40:18.973 Info Server: http/1.1 Response 404 to ‌‍‍10.0.1.9‌. Time: 1ms. GET http://‌‍‍emby‌:8096/Users/XXXXXXXXXX/Images/Primary?fillWidth=100&quality=50
2024-12-04 13:40:18.978 Error Server: Error processing request
	*** Error Report ***
	Version: 4.8.10.0
	Command line: /opt/emby-server/system/EmbyServer.dll -programdata /var/lib/emby -ffdetect /opt/emby-server/bin/ffdetect -ffmpeg /opt/emby-server/bin/ffmpeg -ffprobe /opt/emby-server/bin/ffprobe -restartexitcode 3 -updatepackage emby-server-deb_{version}_amd64.deb
	Operating system: Linux version 6.8.12-2-pve (build@proxmox) (gcc (Debian 12.2.0-14) 12.2.0, GNU ld (GNU Binutils for Debian) 2.40) #1 SMP PREEMPT_DYNAMIC PMX 6.8.12-2
	Framework: .NET 6.0.31
	OS/Process: x64/x64
	Runtime: opt/emby-server/system/System.Private.CoreLib.dll
	Processor count: 56
	Data path: /var/lib/emby
	Application path: /opt/emby-server/system
	System.FormatException: System.FormatException: Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).
	   at System.Guid.GuidResult.SetFailure(Boolean overflow, String failureMessageID)
	   at System.Guid.TryParseExactN(ReadOnlySpan`1 guidString, GuidResult& result)
	   at System.Guid.TryParseGuid(ReadOnlySpan`1 guidString, GuidResult& result)
	   at Emby.Server.Implementations.Library.LibraryManager.GetInternalId(ReadOnlySpan`1 id)
	   at Emby.Server.Implementations.Library.LibraryManager.GetInternalId(String id)
	   at Emby.Api.Images.ImageService.Get(GetItemImage request)
	   at Emby.Server.Implementations.Services.ServiceController.Execute(HttpListenerHost appHost, Object requestDto, IRequest req, Type serviceType)
	   at Emby.Server.Implementations.Services.ServiceHandler.ProcessRequestAsync(HttpListenerHost httpHost, IServerApplicationHost appHost, IRequest httpReq, IResponse httpRes, IStreamHelper streamHelper, RestPath restPath, String responseContentType, CancellationToken cancellationToken)
	   at Emby.Server.Implementations.HttpServer.HttpListenerHost.RequestHandler(IRequest httpReq, ReadOnlyMemory`1 urlString, ReadOnlyMemory`1 localPath, CancellationToken cancellationToken)
	Source: System.Private.CoreLib
	TargetSite: Void SetFailure(Boolean, System.String)`

**Comment by brikim** [comment]
@needo37 I have almost the exact same setup and everything is working. 
Did you set the environment variable
IS_EMBY_API: true
for you jellystat container?
