### ISSUE TITLE
Docker Image - App_Config Does Not Exist

### ISSUE THREAD

**Issue by Jpkribs** [CyferShepard/Jellystat#4]
On a new Postgres DB, I am getting the error:

[0] Error occurred while executing query: error: relation "app_config" does not exist
[0]     at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:287:98)
[0]     at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)
[0]     at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)
[0]     at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)
[0]     at Socket.emit (node:events:512:28)
[0]     at addChunk (node:internal/streams/readable:324:12)
[0]     at readableAddChunk (node:internal/streams/readable:297:9)
[0]     at Readable.push (node:internal/streams/readable:234:10)
[0]     at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
[0]   length: 109,
[0]   severity: 'ERROR',
[0]   code: '42P01',
[0]   detail: undefined,
[0]   hint: undefined,
[0]   position: '15',
[0]   internalPosition: undefined,
[0]   internalQuery: undefined,
[0]   where: undefined,
[0]   schema: undefined,
[0]   table: undefined,
[0]   column: undefined,
[0]   dataType: undefined,
[0]   constraint: undefined,
[0]   file: 'parse_relation.c',
[0]   line: '1392',
[0]   routine: 'parserOpenTable'
[0] }

I am using the following Docker Compose for this:

#############################################

services:

  postgresql-jellystat:
    image: "postgres:latest"
    container_name: "PostgreSQL-JellyStat"
    networks:
      intranet:
        ipv4_address: "100.0.1.2"
    environment:
     - TZ=American/Denver
     - PUID=1010
     - PGID=1003
     - POSTGRES_PASSWORD=Uckeb16UQLo4GWt25
     - POSTGRES_USER=postgres
    volumes:
      - /docker/data/postgresql/jellystat/config/database:/var/lib/postgresql/data
    restart: unless-stopped
      
  jellystat:
    image: cyfershepard/jellystat:latest
    container_name: "JellyStat"
    networks:
      intranet:
        ipv4_address: "100.0.1.3"
    environment:
     - TZ=American/Denver
     - PUID=1010
     - PGID=1003
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=Uckeb16UQLo4GWt25
     - POSTGRES_IP=postgresql-jellystat
     - POSTGRES_PORT=5432
     - JWT_SECRET='Uckeb16UQLo4GWt25'
    ports:
      - "11030:3000"
    depends_on:
      - postgresql-jellystat

networks:

  intranet:
    name: "intranet"
    driver: bridge
    ipam:
      config:
      - subnet: "100.0.0.0/16"
        gateway: "100.0.0.1"

#############################################

As a result of this, the Create User screen gets stuck here:

![image](https://user-images.githubusercontent.com/37599297/230524382-e8167202-1529-4b24-8a96-4081acfcfa78.png)

**Comment by Jpkribs** [comment]
I was actually able to fix this! in [Jellystat](https://github.com/CyferShepard/Jellystat)/[backend](https://github.com/CyferShepard/Jellystat/tree/main/backend)/[postgres-image](https://github.com/CyferShepard/Jellystat/tree/main/backend/postgres-image)/Dockerfile

I changed it from COPY to ADD and this resolved.

**Comment by Jpkribs** [comment]
Scratch that. I don't think that was the resolution. What seems to work is starting the Postgres DB without the DB jfstat. Then start JellyStat. You'll get an error that says "DB jfstat does not exist." Then restart Postgres with the db jfstat enabled. 

No idea what's going on there. Most likely a me and Postgres issue.

**Comment by CyferShepard** [comment]
Hi, il try and replicate this on my end. It may be that the auto initialization process, where if its able to connect to postgres but it cant find the db, it will throw that error "DB jfstat does not exist." and then attempt to initialize it using the script init.sql. I'll try to see whats going on there.

**Comment by fabieng83** [comment]
i have a similar issue , 
i don't like compose so i did a 

```
docker run -d \
  --name jellystat-db \
  -e POSTGRES_USER=postgres \
  -e POSTGRES_PASSWORD=mypassword \
  postgres
```
and a 

```
docker run -d \
  --name jellystat \
  -e POSTGRES_USER=postgres \
  -e POSTGRES_PASSWORD=mypassword \
  -e POSTGRES_IP=jellystat-db \
  -e POSTGRES_PORT=5432 \
  -e JWT_SECRET='my-secret-jwt-key' \
  -p 3000:3000 \
  cyfershepard/jellystat:latest
```

the container are running and 'im stuck at validating after trying to create a user

in the  jellystat logs i have these logs :

```

[0] Error occurred while executing query: Error: getaddrinfo ENOTFOUND jellystat-db
[0]     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26) {
[0]   errno: -3007,
[0]   code: 'ENOTFOUND',
[0]   syscall: 'getaddrinfo',
[0]   hostname: 'jellystat-db'
[0] }
[0] TypeError: Cannot destructure property 'rows' of '(intermediate value)' as it is undefined.
[0]     at /app/backend/auth.js:64:22
[0]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[0] Error occurred while executing query: Error: getaddrinfo ENOTFOUND jellystat-db
[0]     at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26) {
[0]   errno: -3007,
[0]   code: 'ENOTFOUND',
[0]   syscall: 'getaddrinfo',
[0]   hostname: 'jellystat-db'
```

and no error on the postgres container

**Comment by CyferShepard** [comment]
hi @fabieng83 , your issue seems separate from this one, can you confirm if both Docker containers on the same network ?  

I see you specified the hostname as the ip, that should only work if they both are on the same docker-network. 

If not, maybe try adding them to the same network, or expose a port on your postgres container, then change the POSTGRES_IP and POSTGRES_PORT in jellystat to the ip of your postgres container and the port you exposed

**Comment by fabieng83** [comment]
yes they are on the same computer , 
i just did a `netstat -tlp` and it look like the postgres server is not opening a listing port
i"m going to try to add a -p 5432:5432 to the postgres docker run command

**Comment by Jpkribs** [comment]
@CyferShepard 

I don't know if this is helpful, but I have been able to get this to work 100% of the time by following these workaround:

Spin up a brand new Postgres database WITHOUT the environment flag:

 - POSTGRES_DB=jfstat

JellyStat throws the error that the "jfstat" database does not exist.

Restart Postgres, but this time WITH the environment flag:

 - POSTGRES_DB=jfstat

I have performed the same steps four times and it always works. I could just be getting some funky Postgres stuff because I'm not familiar with it. But, I hope that helps!

**Comment by CyferShepard** [comment]
Yes this does make sense now, i didn't see the POSTGRES_DB flag in your docker command earlier. 

Did a little digging and it turns out that the postgres container accepts a flag called POSTGRES_DB which allows you to rename the default db on a fresh install.

Jellystat attempts to connect to the default databasecreated and not the name you provided, it does this to establish a db connection and them attempt to validate if the jfstat database has been initialized, if not, it creates the database jfstat and the necessary tables and functions.

Hope this make sense

**Comment by Dan6erbond** [comment]
Hey! I just came across this behavior, and it seems really problematic for shared databases and in general automation. Why doesn't JFStat simply try to apply migrations?

In my setup I create the `jfstat` DB for it, and get this error:

```js
[0] Error occurred while executing query: error: relation "app_config" does not exist
[0]     at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:287:98)
[0]     at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)
[0]     at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)
[0]     at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)
[0]     at Socket.emit (node:events:512:28)
[0]     at addChunk (node:internal/streams/readable:324:12)
[0]     at readableAddChunk (node:internal/streams/readable:297:9)
[0]     at Readable.push (node:internal/streams/readable:234:10)
[0]     at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
[0]   length: 109,
[0]   severity: 'ERROR',
[0]   code: '42P01',
[0]   detail: undefined,
[0]   hint: undefined,
[0]   position: '15',
[0]   internalPosition: undefined,
[0]   internalQuery: undefined,
[0]   where: undefined,
[0]   schema: undefined,
[0]   table: undefined,
[0]   column: undefined,
[0]   dataType: undefined,
[0]   constraint: undefined,
[0]   file: 'parse_relation.c',
[0]   line: '1381',
[0]   routine: 'parserOpenTable'
[0] }```

Would it be possible to have it just run the migrations on start? Or how can I run them manually?

**Comment by CyferShepard** [comment]
Hi @Dan6erbond , to be honest this is my first time using postgres so im still figuring out some of its functionality. I actually didn't know about migrations and i will definitely look into this as in the future i will be making changes to the database. 

For now, there is no need to create the database, as long as you have the default table name in postgres, once jellystat connects, itl initialize the db jfstat. If you would like to set it up manually check this file https://github.com/CyferShepard/Jellystat/blob/main/backend/init.sql ,this is the script needed to create the db and necessary tables and functions.

**Comment by CyferShepard** [comment]
Just an update. I have implemented migrations. Just having a minor issue but this should be added within the next day or so which will fix this bug

For now, the steps to avoid this would be to ensure that the default db 'postgres' exists and not to create the db 'jfstat' manually. 

If you do want to create it manually, ensure to use the init.sql script mentioned above.

**Comment by Dan6erbond** [comment]
@CyferShepard I attempted to run the `init.sql`, but it references the `postgres` role and possibly other generic values that need to be changed. I have a shared Postgres instance for all my apps, and only allow them to access their DBs using a role I create for them. Migrations should be contained in a way that doesn't break these principles IMO since otherwise it makes too many assumptions about the setup.

**Comment by CyferShepard** [comment]
A Fix has been pushed, please try the latest image and let me know, I scrapped the old process and implemented migrations. Hopefully this will allow for more stable first time setup.

**Comment by CyferShepard** [comment]
@renetsk your issue seems separate from this. Can you provide more details on this bug in #7

**Comment by Dan6erbond** [comment]
Hey! Yes, your latest release fixes the issue, but I noticed a different error that had me going over the code a bit more:

```js
[0] error: database "jellystat" does not exist
[0]     at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:287:98)
[0]     at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)
[0]     at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)
[0]     at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)
[0]     at Socket.emit (node:events:512:28)
[0]     at addChunk (node:internal/streams/readable:324:12)
[0]     at readableAddChunk (node:internal/streams/readable:297:9)
[0]     at Readable.push (node:internal/streams/readable:234:10)
[0]     at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```

You should consider using environment variables for the DB as well, instead of hardcoding `jellystat`/`jfstat` everywhere.

I also noticed this [line in server.js](https://github.com/CyferShepard/Jellystat/blob/main/backend/server.js#L16), that seems to use development configs for the production environment as well.

**Comment by CyferShepard** [comment]
Hi @Dan6erbond , the project is still in early development phase so I decided to leave all flags in development mode. This repo is just so that if anyone wants to assist with development they can. I should probably put a disclaimer stating its in early development mode. 

Il implement the above in the next fix so that shouldn't be an issue. In regards to your issue can you tell me what you where doing or at what part of the application this error occurred, I just double checked and can confirm the db name was hardcoded as 'jfstat' so im abit puzzled as to why its looking for 'jellystat'.
